version: "3.5"
services:
  db:
    container_name: wb
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=wb_shop
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  nats:
    image: nats-streaming:latest
    command: ["-cid", "wb"]
    ports:
      - "4222:4222"
    hostname: nats-server

volumes:
  db:
